@startuml
package field {
~class Cell {
    ~Sign sign
    ~enum Sign 

    ~Cell() 
    ~void setSign(Sign sign) 
    ~Sign getSign() 
}
+class Point {
    -int column
    -int row

    +Point(int column, int row) 
    +int getColumn() 
    +int getRow() 
}
}
@endtuml
